name: Generate release-artifacts
on:
  release:
    types:
      - created
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/amd64, linux/arm64, linux/arm, linux/mips, linux/386"
          package: ""
          name: "dupont"
          compress: "false"
          dest: "dist"
